=== SameerFaisal/2210B1---XSLT/XSLT Tutorial/style.dtd
<!ELEMENT class (student,student)>
    <!ELEMENT student (firstName,lastName,nickName)>
    <!ELEMENT firstName (#PCDATA)>
    <!ELEMENT lastName (#PCDATA)>
    <!ELEMENT nickName (#PCDATA)>

=== SameerFaisal/2210B1---XSLT/XSLT Tutorial/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl" ?>
<!DOCTYPE class SYSTEM "style.dtd">
<class>

<student>
<firstName>
Graham
</firstName>
<lastName>
Bell
</lastName>
<nickName>
Garry
</nickName>
</student>
<student>
    <firstName>
    Sameer
    </firstName>
    <lastName>
    Faisal
    </lastName>
    <nickName>
    Sam
    </nickName>
    </student>
</class>
